# A project name is equivalent to a source file in which user_main() resides
SMAC_PROJECT = blink

# Add additional source files here
PROJECT_SOURCEFILES +=

# Define the platform to which this project is going to be built
TARGET = cc2530dk

all: $(SMAC_PROJECT)

SMAC = ../..

include $(SMAC)/Makefile.include
